spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tehran
    username: root
    password: mysecretpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Optional: init schema on startup
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE